config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Defines the root path route ("/")
  resources :users do
      resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:create, :new]
      resources :likes, only: [:create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          resources :comments
          resources :likes
        end
      end
    end
  end
  root 'users#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Handle the case where we don't have a current_user i.e. the user is a guest
    user ||= User.new

    if user.is? :admin
      can :manage, :all
    else
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
      can :manage, Like, author_id: user.id
      can :read, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: :User
  belongs_to :post
  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: :User
  belongs_to :post
  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: :User
  has_many :likes
  has_many :comments
  def update_posts_counter
    user.increment!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'author_id'
  has_many :likes
  has_many :comments
  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  # Roles = [:admin, :default]

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  def index
    @post = Post.find(params[:post_id])
    render json: @post.comments
  end

  def create
    @post = Post.find(params[:post_id])
    current_user = User.find(params[:user_id])
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = posts.id
    if @comment.save
      render json: @comment, status: :created
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = @user.posts
    render json: @post
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    # @current_user = User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    post_id = params[:post_id].to_i
    post = Post.find(post_id)
    text = params[:comment][:text]
    @comment = Comment.new(text:, author: current_user, post:)
    if @comment.save
      flash[:success] = 'Comment created successfully!'
      redirect_to user_posts_url
    else
      flash.now[:error] = 'Oops, Something went wrong!'
      render :new
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post_id = params[:post_id].to_i
    post = Post.find(post_id)
    like = Like.new(author: current_user, post:)
    if like.save
      redirect_to user_posts_url
    else
      flash[:error] = 'Oops, Something went wrong!'
      render user_posts_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @current_user = User.find_by!(id: params[:user_id])
    @posts = Post.where(author_id: @current_user)
  end

  def new
    @new_post = Post.new
  end

  def show
    @current_user = User.find_by!(id: params[:user_id])
    @posts = Post.where(author_id: @current_user)
    @post = @posts.find(params[:id])
  end

  def create
    title = params[:post][:title]
    text = params[:post][:text]
    @post = Post.new(title:, text:, comments_counter: 0, likes_counter: 0, author: current_user)
    if @post.save
      flash[:success] = 'Post saved successfully.'
      redirect_to user_posts_url
    else
      flash.now[:error] = 'Error: Post could not be saved'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class='comment-form'>
  <%= form_with model: @comment, url: user_post_comments_path do |form| %>
    <%=form.text_area :text, placeholder: 'comment content'%><br>
    <%=form.submit 'add comment'%>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="root-container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/index.html.erb
<%=render partial:'shared/user', locals: {user: @current_user}%>
<%=render partial: 'shared/post', collection: @posts, locals: {user: @current_user}%>
<hr>
<%@posts.each do |comment|%>
<h4>Users comment on this post</h4>
<%=render partial: 'shared/comment', collection: comment.recent_comments%>
<%end%><br><br>
<%= button_to 'Pagination', users_path, class: 'btn-all-post button' %>

app/views/posts/new.html.erb
<div>
<%=form_with model: @new_post, url: user_posts_path  do |form| %>
<div class='post-title'>
<%=form.label :title%>
<%=form.text_field :title%>
</div><br>
<div class='post-content'>
<%=form.label :text%>
<%=form.text_area :text%>
</div><br>
<%=form.submit 'Post'%>
<%end%>
</div>

app/views/posts/show.html.erb
<%=render partial: 'shared/post', locals:{post: @post}%>
<h4>Users comment on this post</h4>
<%=render partial: 'shared/comment', collection: @post.recent_comments%>

app/views/shared/_comment.html.erb
<div class='comment'>
  <p><strong><%=comment.author.name%> </strong> : <span><%=comment.text%></span></p>
  <%if can? :destroy, Comment%>
    <%= button_to "Delete Comment", "/users/#{comment.author.id}/posts/#{comment.post.id}/comments/#{comment.id}", method: :delete, class: 'btn-comment button'%>
  <%end%>
</div>

app/views/shared/_post.html.erb
<div class='card'>
    <h3><%=post.title%></h3>
    <p><%=post.text%></p>
    <div class='like-comment'>
    <div>Comments: <%=post.comments_counter || 0%></div>
    <div>Likes: <%=post.likes_counter || 0%></div>
    </div>
    <% if can? :destroy, post%>
    <%= button_to "Delete Post", "/users/#{user.id}/posts/#{post.id}", method: :delete, class: 'btn-comment button'%>
  <%end%>
</div>

app/views/shared/_user.html.erb
<%= link_to user_path(user), class:'user-link' do %>
<div class='container'>
<div><%= image_tag (user.photo), alt: 'avatar', class:'user-img' if user.photo%></div>
<div class="username">
<h2><%=user.name%></h2>
<p class="number-of-post">Number of Posts:<%=user.posts_counter || 0 %></p>
</div>
</div>
<%end%>

app/views/users/index.html.erb
<%=render partial:'shared/user', collection: @users%>
<%=link_to 'Sign Up here',  '/users/sign_up' %>
<%=link_to 'Sign in',  '/users/sign_in' %>

app/views/users/show.html.erb
<%=render partial:'shared/user', locals: {user: @user}%>

<div class="bio"><%=@user.bio%></div>
<%=render partial: 'shared/post', collection: @user.recent_posts%>